# Generated by Django 6.0 on 2026-01-25 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_customuser_alter_book_options_customuseradmin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
    ]
